=== kgorog989/MPW46D_XMLGyak/MPW46D_1018/XMLSchemaMPW46D.xsd
<?xml version="1.0" encoding="utf-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

<!-- Egyszerű típusok kigyűjtése, saját típusok meghatározása, megszorítás -->

    <xs:element name="név" type="xs:string"/>
    <xs:element name="helyszín" type="xs:string"/>
    <xs:element name="év" type="xs:int"/>
    <xs:element name="ország" type="xs:string"/>
    <xs:element name="díj" type="xs:int"/>
    <xs:element name="adószám" type="xs:int"/>
    <xs:element name="alapítás" type="xs:int"/>
    <xs:element name="bevétel" type="xs:string"/>
    <xs:element name="diákigazolvány" type="xs:string"/>
    <xs:element name="település" type="xs:string"/>
    <xs:element name="utca" type="xs:string"/>
    <xs:element name="házszám" type="xs:string"/>
    <xs:element name="kérdező" type="xs:string"/>
    <xs:element name="nyelv" type="xs:string"/>
    <xs:element name="szint" type="xs:string"/>
    <xs:element name="fizetés" type="xs:int"/>
    <xs:element name="ital" type="xs:string"/>
    <xs:element name="cég" type="xs:string"/>

   <xs:element name="műszak">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="nappali"/>
                <xs:enumeration value="esti"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

<xs:element name="Fesztivál_MPW46D">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="Fesztivál" type="fesztivalTipus" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="Fellépő" type="fellepoTipus" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="Tulajdonos" type="tulajdonosTipus" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="Résztvevő" type="resztvevoTipus" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="közvélemény" type="kozvelemenyTipus" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="Nyelvtudás" type="nyelvtudasTipus" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="Alkalmazott" type="alkalmazottTipus" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="Bár" type="barTipus" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Kulcsok megvalósítása -->
    <xs:key name="fesztivalKey">
        <xs:selector xpath=".//Fesztivál"/>
        <xs:field xpath="@FESZ_ID"/>
    </xs:key>
    <xs:key name="fellepoKey">
        <xs:selector xpath=".//Fellépő"/>
        <xs:field xpath="@FEL_ID"/>
    </xs:key>
    <xs:key name="tulajdonosKey">
        <xs:selector xpath=".//Tulajdonos"/>
        <xs:field xpath="@T_ID"/>
    </xs:key>
    <xs:key name="resztvevoKey">
        <xs:selector xpath=".//Résztvevő"/>
        <xs:field xpath="@R_ID"/>
    </xs:key>
    <xs:key name="kozvelemenyKey">
        <xs:selector xpath=".//közvélemény"/>
        <xs:field xpath="@K_ID"/>
    </xs:key>
    <xs:key name="nyelvtudasKey">
        <xs:selector xpath=".//Nyelvtudás"/>
        <xs:field xpath="@NY_ID"/>
    </xs:key>
    <xs:key name="alkalmazottKey">
        <xs:selector xpath=".//Alkalmazott"/>
        <xs:field xpath="@A_ID"/>
    </xs:key>
    <xs:key name="barKey">
        <xs:selector xpath=".//Bár"/>
        <xs:field xpath="@B_ID"/>
    </xs:key>
  
    <!-- Idegenkulcsok megvalósítása -->
    <xs:keyref name="fesztivalTulajdonosKeyRef" refer="fesztivalKey">
        <xs:selector xpath=".//Tulajdonos"/>
        <xs:field xpath="@T_ID"/>
    </xs:keyref>
    <xs:keyref name="fesztivalFellepoKeyRef" refer="fesztivalKey">
        <xs:selector xpath=".//Fellépő"/>
        <xs:field xpath="@FESZ_IDREF"/>
    </xs:keyref>
    <xs:keyref name="fesztivalResztvevoKeyRef" refer="fesztivalKey">
        <xs:selector xpath=".//Résztvevő"/>
        <xs:field xpath="@FESZ_IDREF"/>
    </xs:keyref>
    <xs:keyref name="fesztivalBarKeyRef" refer="fesztivalKey">
        <xs:selector xpath=".//Bár"/>
        <xs:field xpath="@FESZ_IDREF"/>
    </xs:keyref>
    <xs:keyref name="resztvevoKeyRef" refer="resztvevoKey">
        <xs:selector xpath=".//közvélemény"/>
        <xs:field xpath="@R_IDREF"/>
    </xs:keyref>
    <xs:keyref name="nyelvtudasKeyRef" refer="nyelvtudasKey">
        <xs:selector xpath=".//közvélemény"/>
        <xs:field xpath="@NY_IDREF"/>
    </xs:keyref>
    <xs:keyref name="barKeyRef" refer="barKey">
        <xs:selector xpath=".//Alkalmazott"/>
        <xs:field xpath="@B_IDREF"/>
    </xs:keyref>

    <!-- 1:1 kapcsolat-->
    <xs:unique name="tulajdonosKeyUnique">
        <xs:selector xpath=".//Tulajdonos"/>
        <xs:field xpath="@FESZ_ID"/>
    </xs:unique>
</xs:element>


<xs:complexType name="fesztivalTipus">
    <xs:sequence>
        <xs:element ref="név"/>
        <xs:element ref="helyszín"/>
        <xs:element ref="év"/>
    </xs:sequence>
    <xs:attribute ref="FESZ_ID"/>
</xs:complexType>

<xs:complexType name="fellepoTipus">
    <xs:sequence>
        <xs:element ref="név"/>
        <xs:element ref="ország"/>
        <xs:element ref="díj"/>
    </xs:sequence>
    <xs:attribute ref="FEL_ID"/>
    <xs:attribute ref="FESZ_IDREF"/>
</xs:complexType>

<xs:complexType name="tulajdonosTipus">
    <xs:sequence>
        <xs:element ref="név"/>
        <xs:element ref="adószám"/>
        <xs:element ref="alapítás"/>
        <xs:element ref="bevétel"/>
    </xs:sequence>
    <xs:attribute ref="T_ID"/>
</xs:complexType>

<xs:complexType name="resztvevoTipus">
    <xs:sequence>
        <xs:element ref="név"/>
        <xs:element ref="diákigazolvány"  minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="lakcím" type="lakcimTipus"/>
    </xs:sequence>
    <xs:attribute ref="R_ID"/>
    <xs:attribute ref="FESZ_IDREF"/>
</xs:complexType>

<xs:complexType name="kozvelemenyTipus">
    <xs:sequence>
        <xs:element ref="kérdező"/>
    </xs:sequence>
    <xs:attribute ref="K_ID"/>
    <xs:attribute ref="R_IDREF"/>
    <xs:attribute ref="NY_IDREF"/>
</xs:complexType>

<xs:complexType name="nyelvtudasTipus">
    <xs:sequence>
        <xs:element ref="nyelv"/>
        <xs:element ref="szint"/>
    </xs:sequence>
    <xs:attribute ref="NY_ID"/>
</xs:complexType>

<xs:complexType name="alkalmazottTipus">
    <xs:sequence>
        <xs:element ref="név"/>
        <xs:element ref="műszak" minOccurs="1" maxOccurs="unbounded"/>
        <xs:element ref="fizetés"/>
    </xs:sequence>
    <xs:attribute ref="A_ID"/>
    <xs:attribute ref="B_IDREF"/>
</xs:complexType>

<xs:complexType name="barTipus">
    <xs:sequence>
        <xs:element ref="név"/>
        <xs:element ref="ital" minOccurs="1" maxOccurs="unbounded"/>
        <xs:element ref="cég"/>
    </xs:sequence>
    <xs:attribute ref="B_ID"/>
    <xs:attribute ref="FESZ_IDREF"/>
</xs:complexType>

<xs:complexType name="lakcimTipus">
    <xs:sequence>
        <xs:element ref="település"/>
        <xs:element ref="utca"/>
        <xs:element ref="házszám"/>
    </xs:sequence>
</xs:complexType>

<!-- kulcsok-->

    <xs:attribute name="FESZ_ID" type="xs:ID"/>
    <xs:attribute name="FEL_ID" type="xs:ID"/>
    <xs:attribute name="R_ID" type="xs:ID"/>
    <xs:attribute name="K_ID" type="xs:ID"/>
    <xs:attribute name="NY_ID" type="xs:ID"/>
    <xs:attribute name="A_ID" type="xs:ID"/>
    <xs:attribute name="B_ID" type="xs:ID"/>

    <xs:attribute name="T_ID" type="xs:IDREF"/>
    <xs:attribute name="FESZ_IDREF" type="xs:IDREF"/>
    <xs:attribute name="R_IDREF" type="xs:IDREF"/>
    <xs:attribute name="NY_IDREF" type="xs:IDREF"/>
    <xs:attribute name="B_IDREF" type="xs:IDREF"/>    

</xs:schema>

=== kgorog989/MPW46D_XMLGyak/MPW46D_1018/XMLMPW46D.xml
<?xml version="1.0" encoding="utf-8"?>

<Fesztivál_MPW46D xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="XMLSchemaMPW46D.xsd">
    <Fesztivál FESZ_ID="">
        <név></név>
        <helyszín></helyszín>
        <év></év>
    </Fesztivál>

    <Fellépő FEL_ID="" FESZ_IDREF="">
        <név></név>
        <ország></ország>
        <díj></díj>
    </Fellépő>

    <Tulajdonos T_ID="">
        <név></név>
        <adószám></adószám>
        <alapítás></alapítás>
        <bevétel></bevétel>
    </Tulajdonos>

    <Résztvevő R_ID="" FESZ_IDREF="">
        <név></név>
        <diákigazolvány></diákigazolvány>
        <lakcím>
            <település></település>    
            <utca></utca>
            <házszám></házszám>
        </lakcím>
    </Résztvevő>

    <közvélemény K_ID="" R_IDREF="" NY_IDREF="">
        <kérdező></kérdező>
    </közvélemény>

    <Nyelvtudás NY_ID="">
        <nyelv></nyelv>    
        <szint></szint>
    </Nyelvtudás>

    <Alkalmazott A_ID="" B_IDREF="">
        <név></név>
        <műszak></műszak>
        <fizetés></fizetés>
    </Alkalmazott>

    <Bár B_ID="" FESZ_IDREF="">   
        <név></név>
        <ital></ital>
        <cég></cég>
    </Bár>

</Fesztivál_MPW46D>
