=== kgorog989/MPW46D_XMLGyak/MPW46D_1004/MPW46D_ertodtd.dtd
<?xml version="1.0" encoding="utf-8"?>

<!ELEMENT MPW46D_modell (A, AB, B, C)>
    <!ELEMENT A (b*, c)>
        <!ELEMENT b (x, y)>
            <!ELEMENT x (#PCDATA)>
            <!ELEMENT y (#PCDATA)>
        <!ELEMENT c (d, e)>
            <!ELEMENT d (#PCDATA)>
            <!ELEMENT e (#PCDATA)>
    <!ELEMENT AB (cAB)> 
        <!ELEMENT cAB (#PCDATA)>
    <!ELEMENT B (bB)>
        <!ELEMENT bB (xb, yb)>
                <!ELEMENT xb (#PCDATA)>
                <!ELEMENT yb (#PCDATA)>
    <!ELEMENT C (b_in_C)>       
        <!ELEMENT b_in_C (#PCDATA)>

<!ATTLIST A  a ID #REQUIRED>
<!ATTLIST B  a ID #REQUIRED>
<!ATTLIST C  a ID #REQUIRED>
<!ATTLIST AB Aref IDREF #REQUIRED>
<!ATTLIST AB Bref IDREF #REQUIRED>
<!ATTLIST B Cref IDREF #REQUIRED>

=== kgorog989/MPW46D_XMLGyak/MPW46D_1004/MPW46D_dtdtoxml.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE MPW46D_modell SYSTEM "MPW46D_ertodtd.dtd">

<MPW46D_modell>
    <A a="Aref">
        <b>
            <x>elementX</x>
            <y>elementY</y>
        </b>
        <c>
            <d>elementD</d>
            <e>elementE</e>
        </c>
    </A>

    <AB Aref="Aref" Bref="Bref">
        <cAB>key</cAB>
    </AB>  

    <B a="Bref" Cref="Cref">
        <bB>
            <xb>elso</xb>
            <yb>masodik</yb>
        </bB>
    </B>

    <C a="Cref">
        <b_in_C>elementB</b_in_C>
    </C>    
</MPW46D_modell>
