=== kgorog989/MPW46D_XMLGyak/MPW46D_1004/MPW46D_orarend.xsd
<?xml version="1.0" encoding="utf-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

<xs:element name="MPW46D_orarend">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="ora" type="oraTipus" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>

<xs:complexType name="oraTipus">
    <xs:sequence>
        <xs:element name="kurzusnev" type="xs:string"/>
        <xs:element name="idopont" type="idopontTipus"/>
        <xs:element name="oktato" type="xs:string"/>
        <xs:element name="helyszin" type="xs:string"/>
        <xs:element name="szak" type="xs:string"/>
    </xs:sequence>
    <xs:attribute name="kod" type="xs:int" use="required"/>
    <xs:attribute name="tipus" type="oraTipusTipus" default="elmelet"/>
</xs:complexType>

<xs:simpleType name="oraTipusTipus">
    <xs:restriction base="xs:string">
        <xs:enumeration value="elmelet"/>
        <xs:enumeration value="gyakorlat"/>
        <xs:enumeration value="elmelet/gyakorlat"/>
    </xs:restriction>
</xs:simpleType>

<xs:complexType name="idopontTipus">
    <xs:sequence>
        <xs:element name="nap" type="napTipus"/>
        <xs:element name="kezdopont" type="idopontOraTipus"/>
        <xs:element name="vegpont" type="idopontOraTipus"/>
    </xs:sequence>
</xs:complexType>

<xs:simpleType name="napTipus">
    <xs:restriction base="xs:string">
        <xs:enumeration value="hétfő"/>
        <xs:enumeration value="kedd"/>
        <xs:enumeration value="szerda"/>
        <xs:enumeration value="csütörtök"/>
        <xs:enumeration value="péntek"/>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="idopontOraTipus">
    <xs:restriction base="xs:positiveInteger">
        <xs:enumeration value="8"/>
        <xs:enumeration value="10"/>
        <xs:enumeration value="12"/>
        <xs:enumeration value="14"/>
        <xs:enumeration value="16"/>
        <xs:enumeration value="18"/>
        <xs:enumeration value="20"/>
    </xs:restriction>
</xs:simpleType>

</xs:schema>

=== kgorog989/MPW46D_XMLGyak/MPW46D_1004/MPW46D_orarend.xml
<?xml version="1.0" encoding="utf-8"?>

<MPW46D_orarend xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="MPW46D_orarend.xsd">

<!--!DOCTYPE MPW46D_orarend SYSTEM "MPW46D_orarend.dtd"-->

    <ora kod="1" tipus="elmelet">
        <kurzusnev>WEB technológiák</kurzusnev>
        <idopont>
            <nap>hétfő</nap>
            <kezdopont>14</kezdopont>
            <vegpont>16</vegpont>
        </idopont>
        <oktato>Agárdi Anita</oktato>
        <helyszin>XXX. előadó</helyszin>
        <szak>PTI</szak>
    </ora>

    <ora kod="2" tipus="gyakorlat">
        <kurzusnev>WEB technológiák</kurzusnev>
        <idopont>
            <nap>hétfő</nap>
            <kezdopont>16</kezdopont>
            <vegpont>18</vegpont>
        </idopont>
        <oktato>Agárdi Anita</oktato>
        <helyszin>inf. 202.</helyszin>
        <szak>PTI</szak>
    </ora>

    <ora kod="3" tipus="elmelet">
        <kurzusnev>Mesterséges intelligencia</kurzusnev>
        <idopont>
            <nap>kedd</nap>
            <kezdopont>10</kezdopont>
            <vegpont>12</vegpont>
        </idopont>
        <oktato>Kunné Dr. Tamás Judit</oktato>
        <helyszin>XXXII. előadó</helyszin>
        <szak>PTI</szak>
    </ora>

    <ora kod="4" tipus="elmelet">
        <kurzusnev>Adatkezelés XML-ben</kurzusnev>
        <idopont>
            <nap>kedd</nap>
            <kezdopont>12</kezdopont>
            <vegpont>14</vegpont>
        </idopont>
        <oktato>Dr. Bednarik László</oktato>
        <helyszin>XXXII. előadó</helyszin>
        <szak>PTI</szak>
    </ora>

    <ora kod="5" tipus="elmelet/gyakorlat">
        <kurzusnev>Algoritmusok és vizsgálatuk</kurzusnev>
        <idopont>
            <nap>kedd</nap>
            <kezdopont>14</kezdopont>
            <vegpont>18</vegpont>
        </idopont>
        <oktato>Dr. Házy Attila</oktato>
        <helyszin>A1/320.</helyszin>
        <szak>PTI</szak>
    </ora>

    <ora kod="6" tipus="gyakorlat">
        <kurzusnev>Adatkezelés XML-ben</kurzusnev>
        <idopont>
            <nap>szerda</nap>
            <kezdopont>12</kezdopont>
            <vegpont>14</vegpont>
        </idopont>
        <oktato>Dr. Bednarik László</oktato>
        <helyszin>inf. 103.</helyszin>
        <szak>PTI</szak>
    </ora>

    <ora kod="7" tipus="elmelet">
        <kurzusnev>Vállalati információs rendszerek</kurzusnev>
        <idopont>
            <nap>szerda</nap>
            <kezdopont>14</kezdopont>
            <vegpont>16</vegpont>
        </idopont>
        <oktato>Dr. Sasvári Péter</oktato>
        <helyszin>inf. 101.</helyszin>
        <szak>PTI</szak>
    </ora>

    <ora kod="8" tipus="gyakorlat">
        <kurzusnev>Vállalati információs rendszerek</kurzusnev>
        <idopont>
            <nap>szerda</nap>
            <kezdopont>18</kezdopont>
            <vegpont>20</vegpont>
        </idopont>
        <oktato>Dr. Sasvári Péter</oktato>
        <helyszin>inf. 101.</helyszin>
        <szak>PTI</szak>
    </ora>

    <ora kod="9" tipus="gyakorlat">
        <kurzusnev>Mesterséges intelligencia</kurzusnev>
        <idopont>
            <nap>csütörtök</nap>
            <kezdopont>10</kezdopont>
            <vegpont>12</vegpont>
        </idopont>
        <oktato>Fazekas Levente</oktato>
        <helyszin>I. előadó</helyszin>
        <szak>PTI</szak>
    </ora>

</MPW46D_orarend>
