=== kgorog989/MPW46D_XMLGyak/MPW46D_1004/MPW46D_kurzusfelvetel.dtd
<?xml version="1.0" encoding="utf-8"?>

<!ELEMENT kurzusfelvetel (kurzusadatok*)>
    <!ELEMENT kurzusadatok (kurzus*, idopont+, (oktato|oraado)?)>
        <!ELEMENT kurzus (#PCDATA)>
        <!ELEMENT idopont (kezdet?, veg?, nap?)>
            <!ELEMENT kezdet (#PCDATA)>
            <!ELEMENT veg (#PCDATA)>
            <!ELEMENT nap (#PCDATA)>
        <!ELEMENT oktato (#PCDATA)>
        <!ELEMENT oraado (#PCDATA)>

<!ATTLIST kurzusadatok jovahagyas (igen|nem) "nem">
<!ATTLIST nap nap (hétfő | kedd | szerda | csütörtök | péntek) "hétfő">

=== kgorog989/MPW46D_XMLGyak/MPW46D_1004/MPW46D_kurzusfelvetel.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE kurzusfelvetel SYSTEM "MPW46D_kurzusfelvetel.dtd">

<kurzusfelvetel>
    <kurzusadatok>
        <kurzus>Adatkezelés XML-ben</kurzus>
        <idopont>
            <kezdet>12</kezdet>
            <veg>14</veg>
            <nap>kedd</nap>
        </idopont>
        <oktato>Dr. Bednarik László</oktato>
    </kurzusadatok>
</kurzusfelvetel>
