=== kgorog989/MPW46D_XMLGyak/MPW46D_1011/MPW46D_kurzusfelvetel.xsd
<?xml version="1.0" encoding="utf-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

<!--egyszerű típusok, kigyűjtése hivatkozás céljából-->

    <xs:element name="hnev" type="xs:string"/>
    <xs:element name="szulev" type="xs:string"/>
    <xs:element name="szak" type="xs:string"/>
    <xs:element name="kurzusnev" type="xs:string"/>
    <xs:element name="kredit" type="xs:int"/>
    <xs:element name="hely" type="xs:string"/>
    <xs:element name="oktato" type="xs:string"/>

<xs:element name="MPW46D_kurzusfelvetel">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="hallgato" type="hallgatoTipus" minOccurs="0" maxOccurs="1"/>
            <xs:element name="kurzusok" type="kurzusokTipus" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="tanev" type="xs:string" use="required"/>
        <xs:attribute name="egyetem" type="xs:string" use="required"/>
    </xs:complexType>
</xs:element>

<xs:complexType name="hallgatoTipus">
    <xs:sequence>
        <xs:element ref="hnev"/>
        <xs:element ref="szulev"/>
        <xs:element ref="szak"/>
    </xs:sequence>
    <xs:attribute name="evf" type="xs:int" use="required"/>
</xs:complexType>

<xs:complexType name="kurzusokTipus">
    <xs:sequence>
        <xs:element name="kurzus" type="kurzusTipus" minOccurs="0" maxOccurs="20"/>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="kurzusTipus">
    <xs:sequence>
        <xs:element ref="kurzusnev"/>
        <xs:element ref="kredit"/>
        <xs:element ref="hely"/>
        <xs:element name="idopont" type="idopontTipus"/>
        <xs:element ref="oktato"/>
    </xs:sequence>
    <xs:attribute name="id" type="xs:string" use="required"/>
    <xs:attribute name="jovahagyas" type="jovahagyasTipus" use="required"/>
</xs:complexType>

<xs:simpleType name="jovahagyasTipus">
    <xs:restriction base="xs:string">
        <xs:enumeration value="igen"/>
        <xs:enumeration value="nem"/>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="oraTipusTipus">
    <xs:restriction base="xs:string">
        <xs:enumeration value="elmelet"/>
        <xs:enumeration value="gyakorlat"/>
    </xs:restriction>
</xs:simpleType>

<xs:complexType name="idopontTipus">
    <xs:sequence>
        <xs:element name="nap" type="napTipus"/>
        <xs:element name="kezdopont" type="idopontOraTipus"/>
        <xs:element name="vegpont" type="idopontOraTipus"/>
    </xs:sequence>
</xs:complexType>

<xs:simpleType name="napTipus">
    <xs:restriction base="xs:string">
        <xs:enumeration value="hétfő"/>
        <xs:enumeration value="kedd"/>
        <xs:enumeration value="szerda"/>
        <xs:enumeration value="csütörtök"/>
        <xs:enumeration value="péntek"/>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="idopontOraTipus">
    <xs:restriction base="xs:positiveInteger">
        <xs:enumeration value="8"/>
        <xs:enumeration value="10"/>
        <xs:enumeration value="12"/>
        <xs:enumeration value="14"/>
        <xs:enumeration value="16"/>
        <xs:enumeration value="18"/>
        <xs:enumeration value="20"/>
    </xs:restriction>
</xs:simpleType>

</xs:schema>

=== kgorog989/MPW46D_XMLGyak/MPW46D_1122/xPathMPW46D_2/kurzusfelvetelMPW46D_1.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?><MPW46D_kurzusfelvetel xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" egyetem="ME" tanev="2023/24 I." xs:noNamespaceSchemaLocation="MPW46D_kurzusfelvetel.xsd">
    <hallgato evf="3">
        <hnev>Nagy Tamás</hnev>
        <szulev>2002-06-14</szulev>
        <szak>programtervező informatikus</szak>
    </hallgato>

    <kurzusok>
        <kurzus id="GEIAL331-B" jovahagyas="igen">
            <kurzusnev>WEB technológiák I.</kurzusnev>
            <kredit>5</kredit>
            <hely>XXX.</hely>
            <idopont>
                <nap>hétfő</nap>
                <kezdopont>14</kezdopont>
                <vegpont>16</vegpont>
            </idopont>
            <oktato>Dr. Agárdi Anita</oktato>
        </kurzus>

        <kurzus id="GEIAL331-B gy" jovahagyas="igen">
            <kurzusnev>Matematika</kurzusnev>
            <kredit>5</kredit>
            <hely>inf/202.</hely>
            <idopont>
                <nap>hétfő</nap>
                <kezdopont>16</kezdopont>
                <vegpont>18</vegpont>
            </idopont>
            <oktato>Dr. Agárdi Anita</oktato>
        </kurzus>

        <kurzus id="GEIAK130-B" jovahagyas="igen">
            <kurzusnev>Mesterséges intelligencia</kurzusnev>
            <kredit>5</kredit>
            <hely>XXXII.</hely>
            <idopont>
                <nap>kedd</nap>
                <kezdopont>10</kezdopont>
                <vegpont>12</vegpont>
            </idopont>
            <oktato>Kunné Dr. Tamás Judit</oktato>
        </kurzus>

        <kurzus id="GEIAL332-B" jovahagyas="igen">
            <kurzusnev>Adatkezelés XML-ben</kurzusnev>
            <kredit>5</kredit>
            <hely>XXXII.</hely>
            <idopont>
                <nap>kedd</nap>
                <kezdopont>12</kezdopont>
                <vegpont>14</vegpont>
            </idopont>
            <oktato>Dr. Bednarik László</oktato>
        </kurzus>

        <kurzus id="GEMAK234-B" jovahagyas="igen">
            <kurzusnev>Algoritmusok és vizsgálatuk</kurzusnev>
            <kredit>5</kredit>
            <hely>A1/320.</hely>
            <idopont>
                <nap>kedd</nap>
                <kezdopont>14</kezdopont>
                <vegpont>18</vegpont>
            </idopont>
            <oktato>Dr. Házy Attila</oktato>
        </kurzus>

        <kurzus id="GEIAL332-B" jovahagyas="igen">
            <kurzusnev>Adatkezelés XML-ben</kurzusnev>
            <kredit>5</kredit>
            <hely>inf/103.</hely>
            <idopont>
                <nap>szerda</nap>
                <kezdopont>12</kezdopont>
                <vegpont>14</vegpont>
            </idopont>
            <oktato>Dr. Bednarik László</oktato>
        </kurzus>

        <kurzus id="GEIAL315-B" jovahagyas="igen">
            <kurzusnev>Vállalati információs rendszerek fejlesztése</kurzusnev>
            <kredit>5</kredit>
            <hely>inf/101.</hely>
            <idopont>
                <nap>szerda</nap>
                <kezdopont>14</kezdopont>
                <vegpont>16</vegpont>
            </idopont>
            <oktato>Dr. Sasvári Péter</oktato>
        </kurzus>

        <kurzus id="GEIAL315-B gy" jovahagyas="igen">
            <kurzusnev>Vállalati információs rendszerek fejlesztése</kurzusnev>
            <kredit>5</kredit>
            <hely>inf/101.</hely>
            <idopont>
                <nap>szerda</nap>
                <kezdopont>18</kezdopont>
                <vegpont>20</vegpont>
            </idopont>
            <oktato>Dr. Sasvári Péter</oktato>
        </kurzus>

        <kurzus id="GEIAK130-B gy" jovahagyas="igen">
            <kurzusnev>Mesterséges intelligencia</kurzusnev>
            <kredit>5</kredit>
            <hely>I.</hely>
            <idopont>
                <nap>péntek</nap>
                <kezdopont>10</kezdopont>
                <vegpont>12</vegpont>
            </idopont>
            <oktato>Fazekas Levente</oktato>
        </kurzus>
    </kurzusok>
</MPW46D_kurzusfelvetel>

=== kgorog989/MPW46D_XMLGyak/MPW46D_1011/MPW46D_kurzusfelvetel.xml
<?xml version="1.0" encoding="utf-8"?>

<MPW46D_kurzusfelvetel tanev="2023/24 I." egyetem="ME" xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="MPW46D_kurzusfelvetel.xsd">
    <hallgato evf="3">
        <hnev>Görög Krisztina Erzsébet</hnev>
        <szulev>2002-06-14</szulev>
        <szak>programtervező informatikus</szak>
    </hallgato>

    <kurzusok>
        <kurzus id="MPW46D" jovahagyas="igen">
            <kurzusnev></kurzusnev>
            <kredit></kredit>
            <hely></hely>
            <idopont>
                <nap>hétfő</nap>
                <kezdopont>14</kezdopont>
                <vegpont>16</vegpont>
            </idopont>
            <oktato></oktato>
        </kurzus>
    </kurzusok>
</MPW46D_kurzusfelvetel>
