=== kgorog989/MPW46D_XMLGyak/XMLTaskMPW46D/XMLSchemaMPW46D.xsd
<?xml version="1.0" encoding="utf-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

<!-- Egyszerű típusok kigyűjtése, saját típusok meghatározása, megszorítás -->

    <xs:element name="név" type="xs:string"/>
    <xs:element name="fizetés" type="xs:int"/>
    <xs:element name="beosztás" type="xs:string"/>
    <xs:element name="elérhetőség" type="xs:string"/>
    <xs:element name="város" type="xs:string"/>
    <xs:element name="irányítószám" type="xs:string"/>
    <xs:element name="utca" type="xs:string"/>
    <xs:element name="házszám" type="xs:string"/>
    <xs:element name="egységár" type="xs:int"/>
    <xs:element name="allergének" type="xs:string"/>
    <xs:element name="kezdés" type="xs:string"/>

    <xs:element name="darabszám">
        <xs:simpleType>
            <xs:restriction base="xs:int">
            <xs:minInclusive value="10"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

<!-- komplex típusok-->

<xs:element name="MPW46D_cukrászda">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="dolgozó" type="dolgozóTipus" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="igazgató" type="igazgatóTipus" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="cukrászda" type="cukrászdaTipus" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="árul" type="árulTipus" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="sütemény" type="süteményTipus" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="rendel" type="rendelTipus" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="megrendelő" type="megrendelőTipus" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="rendezvény" type="rendezvényTipus" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <!-- Kulcsok megvalósítása -->
    <xs:key name="dolgozoKey">
        <xs:selector xpath=".//dolgozó"/>
        <xs:field xpath="@DID"/>
    </xs:key>
    <xs:key name="igazgatoKey">
        <xs:selector xpath=".//igazgató"/>
        <xs:field xpath="@IID"/>
    </xs:key>
    <xs:key name="cukraszdaKey">
        <xs:selector xpath=".//cukrászda"/>
        <xs:field xpath="@CID"/>
    </xs:key>
    <xs:key name="sutemenyKey">
        <xs:selector xpath=".//sütemény"/>
        <xs:field xpath="@SID"/>
    </xs:key>
    <xs:key name="megrendeloKey">
        <xs:selector xpath=".//megrendelő"/>
        <xs:field xpath="@MID"/>
    </xs:key>
    <xs:key name="rendezvenyKey">
        <xs:selector xpath=".//rendezvény"/>
        <xs:field xpath="@RID"/>
    </xs:key>

    <!-- Idegenkulcsok megvalósítása -->
    <xs:keyref name="dolgozoKeyRef" refer="cukraszdaKey">
        <xs:selector xpath=".//dolgozó"/>
        <xs:field xpath="@dolgozó_CID"/>
    </xs:keyref>
    <xs:keyref name="arulCukraszdaKeyRef" refer="cukraszdaKey">
        <xs:selector xpath=".//árul"/>
        <xs:field xpath="@árul_CID"/>
    </xs:keyref>
    <xs:keyref name="arulSutemenyKeyRef" refer="sutemenyKey">
        <xs:selector xpath=".//árul"/>
        <xs:field xpath="@árul_SID"/>
    </xs:keyref>
    <xs:keyref name="rendelSutemenyKeyRef" refer="sutemenyKey">
        <xs:selector xpath=".//rendel"/>
        <xs:field xpath="@rendel_SID"/>
    </xs:keyref>
    <xs:keyref name="rendelMegrendeloKeyRef" refer="megrendeloKey">
        <xs:selector xpath=".//rendel"/>
        <xs:field xpath="@rendel_MID"/>
    </xs:keyref>
    <xs:keyref name="rendezvenyMegrendeloKeyRef" refer="megrendeloKey">
        <xs:selector xpath=".//rendezvény"/>
        <xs:field xpath="@rendezvény_MID"/>
    </xs:keyref>

    <xs:keyref name="rendezvenyCukraszdaKeyRef" refer="cukraszdaKey">
        <xs:selector xpath=".//rendezvény"/>
        <xs:field xpath="@rendezvény_CID"/>
    </xs:keyref>

    <!-- 1:1 kapcsolat-->
    <xs:unique name="igazgatoKeyUnique">
        <xs:selector xpath=".//igazgató"/>
        <xs:field xpath="@CID"/>
    </xs:unique>
</xs:element>

<!-- saját típusok-->

<xs:complexType name="dolgozóTipus">
    <xs:sequence>
        <xs:element ref="név"/>
        <xs:element ref="fizetés"/>
        <xs:element ref="beosztás"/>
    </xs:sequence>
    <xs:attribute ref="DID"/>
    <xs:attribute ref="dolgozó_CID"/>
</xs:complexType>

<xs:complexType name="igazgatóTipus">
    <xs:sequence>
        <xs:element ref="név"/>
        <xs:element ref="fizetés"/>
        <xs:element ref="elérhetőség" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute ref="IID"/>
</xs:complexType>

<xs:complexType name="cukrászdaTipus">
    <xs:sequence>
        <xs:element ref="név"/>
        <xs:element name="cím" type="címTipus"/>
    </xs:sequence>
    <xs:attribute ref="CID"/>
</xs:complexType>

<xs:complexType name="árulTipus">
    <xs:attribute ref="árul_CID"/>
    <xs:attribute ref="árul_SID"/>
</xs:complexType>

<xs:complexType name="süteményTipus">
    <xs:sequence>
        <xs:element ref="név"/>
        <xs:element ref="egységár"/>
        <xs:element ref="allergének" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute ref="SID"/>
</xs:complexType>

<xs:complexType name="rendelTipus">
    <xs:sequence>
        <xs:element ref="darabszám"/>
        <xs:element name="összeg" type="xs:int" minOccurs="0" maxOccurs="1"/>
    </xs:sequence>
    <xs:attribute ref="rendel_SID"/>
    <xs:attribute ref="rendel_MID"/>
</xs:complexType>

<xs:complexType name="megrendelőTipus">
    <xs:sequence>
        <xs:element ref="név"/>
        <xs:element ref="elérhetőség" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute ref="MID"/>
</xs:complexType>

<xs:complexType name="rendezvényTipus">
    <xs:sequence>
        <xs:element ref="kezdés"/>
        <xs:element name="helyszín" type="címTipus"/>
    </xs:sequence>
    <xs:attribute ref="RID"/>
    <xs:attribute ref="rendezvény_MID"/>
    <xs:attribute ref="rendezvény_CID"/>
</xs:complexType>

<xs:complexType name="címTipus">
    <xs:sequence>
        <xs:element ref="város"/>
        <xs:element ref="irányítószám"/>
        <xs:element ref="utca"/>
        <xs:element ref="házszám"/>
    </xs:sequence>
</xs:complexType>

<!-- kulcsok-->

    <xs:attribute name="DID" type="xs:ID"/>
    <xs:attribute name="CID" type="xs:ID"/>
    <xs:attribute name="SID" type="xs:ID"/>
    <xs:attribute name="MID" type="xs:ID"/>
    <xs:attribute name="RID" type="xs:ID"/>

    <xs:attribute name="dolgozó_CID" type="xs:IDREF"/>
    <xs:attribute name="árul_CID" type="xs:IDREF"/>
    <xs:attribute name="árul_SID" type="xs:IDREF"/>
    <xs:attribute name="rendel_SID" type="xs:IDREF"/>
    <xs:attribute name="rendel_MID" type="xs:IDREF"/>
    <xs:attribute name="rendezvény_MID" type="xs:IDREF"/>
    <xs:attribute name="rendezvény_CID" type="xs:IDREF"/>

    <!--1:1 kapcsolat megvalósítása-->
    <xs:attribute name="IID" type="xs:IDREF"/>
</xs:schema>

=== kgorog989/MPW46D_XMLGyak/XMLTaskMPW46D/XMLMPW46D.xml
<?xml version="1.0" encoding="utf-8"?>

<MPW46D_cukrászda xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="XMLSchemaMPW46D.xsd">
    <dolgozó DID="" dolgozó_CID="">
        <név></név>    
        <fizetés></fizetés>
        <beosztás></beosztás>
    </dolgozó>

    <igazgató IID="">
        <név></név>    
        <fizetés></fizetés>
        <elérhetőség></elérhetőség>
    </igazgató>

    <cukrászda CID="">
        <név></név>
        <cím>
            <város></város>
            <irányítószám></irányítószám>
            <utca></utca>
            <házszám></házszám>
        </cím>
    </cukrászda>

    <árul árul_CID="" árul_SID=""></árul>

    <sütemény SID="">
        <név></név>
        <egységár></egységár>
        <allergének></allergének>
    </sütemény>

    <rendel rendel_SID="" rendel_MID="">
        <darabszám></darabszám>
        <összeg></összeg>
    </rendel>

    <megrendelő MID="">
        <név></név>
        <elérhetőség></elérhetőség>    
    </megrendelő>

    <rendezvény RID="" rendezvény_MID="" rendezvény_CID="">
        <kezdés></kezdés>
        <helyszín>
            <város></város>
            <irányítószám></irányítószám>
            <utca></utca>
            <házszám></házszám>
        </helyszín>    
    </rendezvény>

</MPW46D_cukrászda>
